"""DEV TOOL - regenerate media/stations/extraShipData_station_kinds.yaml. Not imported by
the addon.

    cd LegendaryMissions
    PYTHONPATH=../sbs_utils python station_kinds/make_station_kinds.py

Copies each race starbase from the stock ship table COMPLETE (the engine rejects, or
crashes on, a trimmed entry) and scales it per kind (STATION_KINDS in station_kinds.py):
meshscale, exclusionradius, hullpoints and shields. Beams stay the race base's. baycount is
dropped - a kind's wings come from its kind, not its hull. `torpedostart: []` is added,
because an entry without one has crashed the engine at load (turret file header).

Ship-data roles are `outpost`, deliberately NOT containing "station": races._is_station is
a substring test, so a `station` role would put these hulls in race_station_hulls and the
ART_KEYS rank pool. The map adds `station` when it spawns one.

The output is JSON-shaped HJSON with a trailing newline - the two things the engine needs
and PyYAML does not (see add_extra in sbs_utils/procedural/ship_data.py).
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
LM = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from sbs_utils.fs import test_set_exe_dir               # noqa: E402
test_set_exe_dir()
from sbs_utils.procedural.ship_data import get_ship_data  # noqa: E402
import station_kinds as K                               # noqa: E402

#: The non-Terran race starbases scaled into kinds.
RACE_BASES = {"kralien": "starbase_kralien", "arvonian": "starbase_arvonian",
              "skaraan": "starbase_skaraan", "torgoth": "starbase_torgoth"}

OUT = os.path.join(LM, "media", "stations", "extraShipData_station_kinds.yaml")

HEADER = """\
# Station KIND hulls - scaled copies of each race's starbase (station_kinds addon).
#
# GENERATED by station_kinds/make_station_kinds.py from the stock ship table. Do not edit
# by hand - change STATION_KINDS in station_kinds.py and regenerate.
#
# Only reaches the engine with EXTRA_SHIP_DATA on; without it the maps spawn the plain race
# starbase for every kind. Entries are complete copies (the engine rejects trimmed ones),
# roles are `outpost` (never "station" - see the generator), and the file must stay
# JSON-shaped with a trailing newline.

"""


def _scaled(entry, race, kind):
    scale = K.STATION_KINDS[kind][0]
    out = json.loads(json.dumps(entry))             # a deep copy of the stock entry
    out.pop("baycount", None)
    out.pop("#mod", None)
    out["key"] = K.station_kind_scaled_key(race, kind)
    out["name"] = f"{race.capitalize()} {K.station_kind_label(kind)} Base"
    out["roles"] = "outpost"
    for field in ("meshscale", "exclusionradius"):
        if field in out:
            out[field] = round(float(out[field]) * scale, 4)
    if "hullpoints" in out:
        out["hullpoints"] = max(1, int(round(float(out["hullpoints"]) * scale)))
    if isinstance(out.get("shields"), list):
        out["shields"] = [max(1, int(round(float(s) * scale))) for s in out["shields"]]
    out.setdefault("torpedostart", [])
    return out


def _main():
    stock = {e.get("key"): e for e in (get_ship_data() or {}).get("#ship-list", [])}
    entries = []
    for race, key in RACE_BASES.items():
        if key not in stock:
            raise SystemExit(f"stock ship table has no {key}")
        for kind in K.STATION_KIND_SCALED:
            entries.append(_scaled(stock[key], race, kind))
    body = json.dumps({"#ship-list": entries}, indent=2)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER + body + "\n")
    print(f"wrote {len(entries)} entries to {OUT}")


if __name__ == "__main__":
    _main()
