"""Station KINDS - Command, Industrial, Science and Civil bases for every race.

Every race but Terran has ONE starbase hull, so a map that builds N enemy bases built N
copies of it - and once station wings went autonomous, N copies of its whole fighter
complement (Deep Strike at difficulty 11 against Arvonians: 11 x 14 fighters). A KIND
separates what a base DOES from what it LOOKS like:

    kind         scale   wings            Terran hull
    command      1.0     Red 4, Gold 4    starbase_command
    industrial   0.8     Red 4            starbase_industry
    science      0.6     Red 2            starbase_science
    civil        0.5     none             starbase_civil

The race provides the art. A non-Terran kind is a SCALED copy of the race's starbase
(`starbase_kralien_industrial`...), declared as extra ship data from the LM media pack -
so it exists only where EXTRA_SHIP_DATA is on and the file reached the engine. Everywhere
else the kind spawns the plain race hull, and still gets the kind's wings, name and role.
Nothing ever spawns a hull the engine was not given (that is `bad allocation`).

A reskin wins: when ART_KEYS maps the race's starbase to another hull (the TNG profile),
every kind uses that hull, unscaled.

The scaled entries are GENERATED by make_station_kinds.py from the stock ship table and
committed - regenerate after changing STATION_KINDS.

Every function is prefixed `station_kind` - one flat MAST namespace.
"""
import random as _random

from sbs_utils.procedural.execution import log
from sbs_utils.procedural.query import to_id
from sbs_utils.procedural.spawn import npc_spawn

#: kind -> (scale, wing count, fighters per wing, Terran hull, display label)
STATION_KINDS = {
    "command": (1.0, 2, 4, "starbase_command", "Command"),
    "industrial": (0.8, 1, 4, "starbase_industry", "Industrial"),
    "science": (0.6, 1, 2, "starbase_science", "Science"),
    "civil": (0.5, 0, 0, "starbase_civil", "Civil"),
}

#: The kinds that get a scaled hull per race (command IS the race's starbase).
STATION_KIND_SCALED = ("industrial", "science", "civil")

#: Logical media path of the generated hulls, WITHOUT extension (the turret convention).
STATION_KIND_SHIP_FILE = "stations/extraShipData_station_kinds"
STATION_KIND_MOD = "LegendaryMissions"


def station_kind_list():
    """The kinds, strongest first."""
    return list(STATION_KINDS)


def station_kind_label(kind):
    """"industrial" -> "Industrial"."""
    return STATION_KINDS.get(kind, (1.0, 0, 0, None, str(kind).capitalize()))[4]


def station_kind_scaled_key(race, kind):
    """The generated hull key for a race's kind: starbase_kralien_industrial."""
    return f"starbase_{str(race).lower()}_{kind}"


def station_kinds_declare_ships():
    """Hand the scaled kind hulls to the engine. Call at story TOP LEVEL - the engine reads
    extra ship data inside create_new_sim(), so a label is too late (the turret reason).

    Returns True when the engine was told. add_extra is itself gated on EXTRA_SHIP_DATA,
    and says so once when it is off. Never raises.
    """
    try:
        from sbs_utils.procedural.ship_data import add_extra
        return bool(add_extra(STATION_KIND_SHIP_FILE, mod=STATION_KIND_MOD))
    except Exception as e:                              # noqa: BLE001
        log(f"station kinds: hulls not declared ({e})", "station_kinds", "warning")
        return False


def station_kind_scaled_live():
    """Are the scaled kind hulls in the ENGINE this mission? Read from the library's own
    load record, which the per-mission reset clears - no latch here to go stale."""
    try:
        from sbs_utils.procedural.ship_data import extra_loaded, extra_ship_data_enabled
    except ImportError:
        return False
    if not extra_ship_data_enabled():
        return False
    stem = STATION_KIND_SHIP_FILE.rpartition("/")[2]
    return any(rec[0] == stem and rec[2] for rec in extra_loaded())


def station_kind_hull(race, kind):
    """The hull to spawn for a race's kind. See the module docstring for the rule."""
    from sbs_utils.procedural.races import race_station_hull
    from sbs_utils.procedural.ship_data import get_ship_data_for, art_key_for
    kind = kind if kind in STATION_KINDS else "command"
    race_key = str(race or "").lower()
    if race_key in ("terran", "tsn", "usfp"):
        return STATION_KINDS[kind][3]
    base = race_station_hull(race_key)
    if base is None:
        return None
    skin = art_key_for(base)
    if skin and skin != base:
        return skin                         # a reskin: every kind wears it, unscaled
    if kind in STATION_KIND_SCALED and station_kind_scaled_live():
        scaled = station_kind_scaled_key(race_key, kind)
        if get_ship_data_for(scaled):
            return scaled
    return base


def station_kind_apply_loadout(station, kind):
    """Give a spawned station its kind's wings. Soft on the hangar addon: without it a
    station simply has no wings to set."""
    from sbs_utils.mast.mast_globals import MastGlobals
    set_size = MastGlobals.globals.get("hangar_wing_set_size")
    if set_size is None:
        try:
            from hangar.hangar_wing import hangar_wing_set_size as set_size
        except ImportError:
            return False
    _scale, count, size, _terran, _label = STATION_KINDS.get(kind, STATION_KINDS["command"])
    set_size(station, size, count)
    return True


def station_kind_spawn(x, y, z, race, kind, name, roles):
    """Spawn a race's base of a kind: its hull, `station_<kind>` added to `roles`, and the
    kind's wing loadout. Returns the station id, or None when the race has no starbase."""
    hull = station_kind_hull(race, kind)
    if hull is None:
        return None
    sid = to_id(npc_spawn(x, y, z, name, f"{roles}, station_{kind}", hull, "behav_station"))
    if sid is None:
        return None
    station_kind_apply_loadout(sid, kind)
    return sid


def station_kind_composition(n, rng=None):
    """The kinds for `n` enemy bases, shuffled with `rng` (a random.Random, or the module
    RNG). A quarter command (at least one), a fifth civil, the rest alternating industrial
    and science - so the fighter total grows with n far slower than n copies of one base.
    """
    n = max(0, int(n))
    if n == 0:
        return []
    command = min(n, max(1, round(n / 4)))
    civil = min(n - command, n // 5)
    rest = n - command - civil
    kinds = ["command"] * command + ["civil"] * civil
    kinds += ["industrial" if i % 2 == 0 else "science" for i in range(rest)]
    (rng or _random).shuffle(kinds)
    return kinds


def station_kind_fighters(kinds):
    """Total fighters a composition fields - for tuning and tests."""
    return sum(STATION_KINDS[k][1] * STATION_KINDS[k][2] for k in kinds)
