name: Crash Report
description: Report a Crash.
title: "[crash]: "
labels: ["bug", "triage"]
# /3 is LegendaryMissions
# /2 is Artemis Cosmos i.e. Engine
# /7 is SBS Library
projects: ["artemis-sbs/9"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: crash_type
    attributes:
      label: Crash Type
      description: What type of crash occured?
      options:
        - Server crash window closed
        - Client crash window closed
        - Assert separate window displayed
        - Cosmos on screen (MAST) error
      default: 0
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: What version of Artemis Cosmos?
      options:
        - v1.0.6
        - v1.0.1
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A crash happened!"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Other details what mission, setup, etc. 
      description: Please enter any other details, including what mission, he operating system, hardware, game modes and difficulty settings, number of clients, type of ships, timing of events, etc.

